config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, :lastname, :address, :phone, :salary, presence: true
  validates :salary, numericality: { only_integer: true }

  def self.to_csv
    headers = ["column one", "column two", "column three"]

    csv_data = CSV.generate(headers: true) do |csv|
      csv << headers
      csv << ["A", "B", "C"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end
#http://127.0.0.1:3000/employees

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
 before_action :set_employee, only: [:show, :edit, :update, :destroy]
  
  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new employee_params
    if @employee.save
      return redirect_to employees_path
    end
    render :new
  end

  def show
  end

 def index
    @allEmployees = Employee.all
    respond_to do |format|
      format.html
      format.csv { send_data @allEmployees.to_csv}
    end
  end

  def edit
  end

  def update
    @employee.update employee_params
    redirect_to @employee
  end

  def destroy
    @employee.destroy
    redirect_to employees_path
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :lastname, :address, :phone, :salary)
  end

  def set_employee
    @employee = Employee.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<br>
<div class="row">
<hr>
<p> 
Name: <%= employee.name %> ㅤId:<%= employee.id%> ㅤ   
<%= link_to "Edit", edit_employee_path(employee) %>
<%= link_to "Delete", employee, method: :delete, data: { confirm: "are you sure to delete this user?" } %> 
<%= link_to "Show",  employee_path(employee) %>
<%= link_to "CSV", method: :csv_cars%> 
</p>
<hr>
</div>

app/views/employees/_form.html.erb
<div class="container">
    <%-  if @employee.errors.any? %>
        <div class="alert alert-danger">
        <h4>Error</h4>
        <%-  if @employee.errors[:name].first%> 
        <p> Name <%= @employee.errors[:name].first%></p>
        <%end%>
        <%-  if @employee.errors[:lastname].first%> 
        <p> LastName <%= @employee.errors[:lastname].first%></p>
        <%end%>
        <%-  if @employee.errors[:address].first%> 
        <p> Address <%= @employee.errors[:address].first%></p>
        <%end%>
        <%-  if @employee.errors[:phone].first%> 
        <p> Phone <%= @employee.errors[:phone].first%></p>
        <%end%>
        <%-  if @employee.errors[:salary].first%> 
        <p> Salary <%= @employee.errors[:salary].first%></p>
        <%end%>
        </div>
    <%end%>
</div>

<div class="form-group">
<%= form_for @employee do |f|%>
    <%= f.label :Name %>
    <br>
    <%= f.text_field :name, class:'form-control' %>
    <br>
    <%= f.label :LastName %>
    <br>
    <%= f.text_field :lastname, class:'form-control' %>
    <br>
    <%= f.label :Address %>
    <br>
    <%= f.text_field :address, class:'form-control' %>
    <br>
    <%= f.label :Phone %>
    <br>
    <%= f.text_field :phone, class:'form-control' %>
    <br>
    <%= f.label :Salary %>
    <br>
    <%= f.text_field :salary, class:'form-control' %>
    <br>
    <%= f.submit 'Save',:class => 'btn btn-primary' %>
    <%= link_to "Home", employees_path,:class => 'btn btn-primary' %>
<% end %>
</div>

app/views/employees/edit.html.erb
<br>
<h1>Edit Employee Data</h1>
<%= render 'form'%>

app/views/employees/index.html.erb
<br>
<div class="row"> 
    <div class="col-10">
        <h1>List of employees</h1>
    </div>
     <div class="col-2 d-flex justify-content-end">
     <%= link_to "Create New Employee", new_employee_path,:class => 'btn btn-primary' %>
    </div>
</div>
<br>
<div class="row">
    <%= render @allEmployees %>
</div>

app/views/employees/new.html.erb
<br>
<h1>Register employee</h1> 
<%= render 'form'%>

app/views/employees/show.html.erb
<br>
<h1>Employee Data</h1> 
<hr>
<h5> The user id is:   <%= @employee.id %> </h5>
<hr>
<h5> The username is:  <%= @employee.name %> </h5>
<hr>
<h5> the user's last name is:   <%= @employee.lastname %> </h5>
<hr>
<h5> the user's address is:   <%= @employee.address %> </h5>
<hr>
<h5> the user's phone number is:   <%= @employee.phone %> </h5>
<hr>
<h5> the user's salary is:   <%= @employee.salary %> </h5>
<hr>
<h5> the user was created:   <%= @employee.created_at %> </h5>
<hr>
<h5> the user was updated:   <%= @employee.updated_at %> </h5>
<hr>
<%= link_to "Home", employees_path,:class => 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoRTesting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
   </div>
  </body>
</html>